version: '1.0'

services:
  cc-login-db:
    image: mysql:latest
    restart: always
    mem_limit: 700m
    ports:
    - "3307:3306"
    networks:
    - cc-network
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: loginDB
    volumes:
      - loginDB-volume:/var/lib/mysql
  cc-employee-db:
      image: mysql:latest
      restart: always
      mem_limit: 700m
      ports:
      - "3308:3306"
      networks:
      - cc-network
      environment:
        MYSQL_ROOT_PASSWORD: "password"
        MYSQL_DATABASE: employeeDB
      volumes:
        - employeeDB-volume:/var/lib/mysql

volumes:
  loginDB-volume:
  employeeDB-volume:
networks:
  cc-network: null
